# Restricted Boltzmann Machines

In [1]:
# Boltzmann Machines
# !pip install torch
# Importing the libraries
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable

In [2]:
# Importing the dataset
movies = pd.read_csv('ml-1m/movies.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
users = pd.read_csv('ml-1m/users.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
ratings = pd.read_csv('ml-1m/ratings.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')

In [3]:
movies.head(20)

0                                      1                             2
0    1                       Toy Story (1995)   Animation|Children's|Comedy
1    2                         Jumanji (1995)  Adventure|Children's|Fantasy
2    3                Grumpier Old Men (1995)                Comedy|Romance
3    4               Waiting to Exhale (1995)                  Comedy|Drama
4    5     Father of the Bride Part II (1995)                        Comedy
5    6                            Heat (1995)         Action|Crime|Thriller
6    7                         Sabrina (1995)                Comedy|Romance
7    8                    Tom and Huck (1995)          Adventure|Children's
8    9                    Sudden Death (1995)                        Action
9   10                       GoldenEye (1995)     Action|Adventure|Thriller
10  11         American President, The (1995)          Comedy|Drama|Romance
11  12     Dracula: Dead and Loving It (1995)                 Comedy|Horror
12  13                           Balto (1995)          Animation|Children's
13  14                           Nixon (1995)                         Drama
14  15                Cutthroat Island (1995)      Action|Adventure|Romance
15  16                          Casino (1995)                Drama|Thriller
16  17           Sense and Sensibility (1995)                 Drama|Romance
17  18                      Four Rooms (1995)                      Thriller
18  19  Ace Ventura: When Nature Calls (1995)                        Comedy
19  20                     Money Train (1995)                        Action

In [4]:
users.head()

0  1   2   3      4
0  1  F   1  10  48067
1  2  M  56  16  70072
2  3  M  25  15  55117
3  4  M  45   7  02460
4  5  M  25  20  55455

In [5]:
ratings.head()

0     1  2          3
0  1  1193  5  978300760
1  1   661  3  978302109
2  1   914  3  978301968
3  1  3408  4  978300275
4  1  2355  5  978824291

In [7]:
# Preparing the training set and the test set
training_set = pd.read_csv('ml-100k/u1.base', delimiter = '\t')
training_set = np.array(training_set, dtype = 'int')
test_set = pd.read_csv('ml-100k/u1.test', delimiter = '\t')
test_set = np.array(test_set, dtype = 'int')

In [8]:
training_set

array([[        1,         2,         3, 876893171],
       [        1,         3,         4, 878542960],
       [        1,         4,         3, 876893119],
       ...,
       [      943,      1188,         3, 888640250],
       [      943,      1228,         3, 888640275],
       [      943,      1330,         3, 888692465]])

In [9]:
test_set

array([[        1,        10,         3, 875693118],
       [        1,        12,         5, 878542960],
       [        1,        14,         5, 874965706],
       ...,
       [      459,       934,         3, 879563639],
       [      460,        10,         3, 882912371],
       [      462,       682,         5, 886365231]])

In [10]:
# Getting the number of users and movies
nb_users = int(max(max(training_set[:,0]), max(test_set[:,0])))
nb_movies = int(max(max(training_set[:,1]), max(test_set[:,1])))

In [11]:
nb_users

943

In [12]:
nb_movies

1682

In [13]:
# Converting the data into an array with users in lines and movies in columns
def convert(data):
    new_data = []
    for id_users in range(1, nb_users + 1):
        id_movies = data[:,1][data[:,0] == id_users]
        id_ratings = data[:,2][data[:,0] == id_users]
        ratings = np.zeros(nb_movies)
        ratings[id_movies - 1] = id_ratings
        new_data.append(list(ratings))
    return new_data
training_set = convert(training_set)
test_set = convert(test_set)

In [16]:
# Converting the data into Torch tensors
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)

In [17]:
# Converting the ratings into binary ratings 1 (Liked) or 0 (Not Liked)
training_set[training_set == 0] = -1
training_set[training_set == 1] = 0
training_set[training_set == 2] = 0
training_set[training_set >= 3] = 1
test_set[test_set == 0] = -1
test_set[test_set == 1] = 0
test_set[test_set == 2] = 0
test_set[test_set >= 3] = 1

In [18]:
# Creating the architecture of the Neural Network
class RBM():
    def __init__(self, nv, nh):
        self.W = torch.randn(nh, nv)
        self.a = torch.randn(1, nh)
        self.b = torch.randn(1, nv)
        
    def sample_h(self, x):
        wx = torch.mm(x, self.W.t())
        activation = wx + self.a.expand_as(wx)
        p_h_given_v = torch.sigmoid(activation)
        return p_h_given_v, torch.bernoulli(p_h_given_v)
    
    def sample_v(self, y):
        wy = torch.mm(y, self.W)
        activation = wy + self.b.expand_as(wy)
        p_v_given_h = torch.sigmoid(activation)
        return p_v_given_h, torch.bernoulli(p_v_given_h)
    
    def train(self, v0, vk, ph0, phk):
        self.W += (torch.mm(v0.t(), ph0) - torch.mm(vk.t(), phk)).t()
        self.b += torch.sum((v0 - vk), 0)
        self.a += torch.sum((ph0 - phk), 0)

nv = len(training_set[0])
nh = 100
rbm = RBM(nv, nh)

In [19]:
# Training the RBM
nb_epoch = 50
batch_size = 100

for epoch in range(1, nb_epoch + 1):
    train_loss = 0
    s = 0.
    for id_user in range(0, nb_users - batch_size, batch_size):
        vk = training_set[id_user : id_user+batch_size]
        v0 = training_set[id_user : id_user+batch_size]
        ph0,_ = rbm.sample_h(v0)
        for k in range(10):
            _,hk = rbm.sample_h(vk)
            _,vk = rbm.sample_v(hk)
            vk[v0<0] = v0[v0<0]
        phk,_ = rbm.sample_h(vk)
        rbm.train(v0, vk, ph0, phk)
        train_loss += torch.mean(torch.abs(v0[v0>=0] - vk[v0>=0]))
        s += 1.
    print('epoch: '+str(epoch)+' loss: '+str(train_loss/s))

epoch: 1 loss: tensor(0.3476)
epoch: 2 loss: tensor(0.2485)
epoch: 3 loss: tensor(0.2496)
epoch: 4 loss: tensor(0.2503)
epoch: 5 loss: tensor(0.2464)
epoch: 6 loss: tensor(0.2447)
epoch: 7 loss: tensor(0.2497)
epoch: 8 loss: tensor(0.2501)
epoch: 9 loss: tensor(0.2468)
epoch: 10 loss: tensor(0.2491)
epoch: 11 loss: tensor(0.2483)
epoch: 12 loss: tensor(0.2486)
epoch: 13 loss: tensor(0.2452)
epoch: 14 loss: tensor(0.2511)
epoch: 15 loss: tensor(0.2484)
epoch: 16 loss: tensor(0.2474)
epoch: 17 loss: tensor(0.2483)
epoch: 18 loss: tensor(0.2453)
epoch: 19 loss: tensor(0.2498)
epoch: 20 loss: tensor(0.2479)
epoch: 21 loss: tensor(0.2470)
epoch: 22 loss: tensor(0.2458)
epoch: 23 loss: tensor(0.2491)
epoch: 24 loss: tensor(0.2458)
epoch: 25 loss: tensor(0.2479)
epoch: 26 loss: tensor(0.2493)
epoch: 27 loss: tensor(0.2460)
epoch: 28 loss: tensor(0.2474)
epoch: 29 loss: tensor(0.2485)
epoch: 30 loss: tensor(0.2464)
epoch: 31 loss: tensor(0.2487)
epoch: 32 loss: tensor(0.2469)
epoch: 33 loss: t

In [20]:
# Testing the RBM
test_loss = 0
s = 0.
for id_user in range(nb_users):
    v = training_set[id_user:id_user+1]
    vt = test_set[id_user:id_user+1]
    if len(vt[vt>=0]) > 0:
        _,h = rbm.sample_h(v)
        _,v = rbm.sample_v(h)
        test_loss += torch.mean(torch.abs(vt[vt>=0] - v[vt>=0]))
        s += 1.
print('test loss: '+str(test_loss/s))

test loss: tensor(0.2333)


In [21]:
h

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
v

tensor([[-1.,  1., -1.,  ..., -1., -1., -1.]])

In [23]:
test_loss

tensor(107.0935)

In [21]:
s

459.0

In [44]:
id_user = 800
v = training_set[id_user:id_user+1]
vt = test_set[id_user:id_user+1]

In [45]:
v[0][1]

tensor(-1.)

In [46]:
movies

0                                   1                             2
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
...    ...                                 ...                           ...
3878  3948             Meet the Parents (2000)                        Comedy
3879  3949          Requiem for a Dream (2000)                         Drama
3880  3950                    Tigerland (2000)                         Drama
3881  3951             Two Family House (2000)                         Drama
3882  3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 3 columns]

In [47]:
phu,h = rbm.sample_h(v)
pvu,v = rbm.sample_v(h)

In [48]:
phu[0][1]

tensor(0.)

In [49]:
pvu[0][1]

tensor(0.7203)

In [50]:
h

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
v[0][1]

tensor(1.)

# FIM